package simx.applications.multimodalinteraction.ontology.functions

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.applications.multimodalinteraction.ontology.types._
import simx.core.ontology.types._

trait Functions {

}