package simx.applications.multimodalinteraction.ontology.functions

/**
 * This file is automatically generated from an ontology.
 * DO NOT EDIT!
 */

import simx.core.entity.description.Interpolator

trait Interpolators {
	implicit val visibleInterpolator: Interpolator[scala.Boolean,simx.core.ontology.Symbols.visible.SymbolType] = new simx.core.ontology.functions.DataTypeBasedLinearInterpolator
}